// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Areas.Admin.Controllers
{
    public partial class AzmoonDegreeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AzmoonDegreeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AzmoonDegreeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteADegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteADegree);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AzmoonDegreeController Actions { get { return MVC.Admin.AzmoonDegree; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AzmoonDegree";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AzmoonDegree";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ListData = "ListData";
            public readonly string AddDegree = "AddDegree";
            public readonly string EditDegree = "EditDegree";
            public readonly string DeleteADegree = "DeleteADegree";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ListData = "ListData";
            public const string AddDegree = "AddDegree";
            public const string EditDegree = "EditDegree";
            public const string DeleteADegree = "DeleteADegree";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ListData s_params_ListData = new ActionParamsClass_ListData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListData ListDataParams { get { return s_params_ListData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListData
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddDegree s_params_AddDegree = new ActionParamsClass_AddDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddDegree AddDegreeParams { get { return s_params_AddDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddDegree
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditDegree s_params_EditDegree = new ActionParamsClass_EditDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDegree EditDegreeParams { get { return s_params_EditDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDegree
        {
            public readonly string AZId = "AZId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteADegree s_params_DeleteADegree = new ActionParamsClass_DeleteADegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteADegree DeleteADegreeParams { get { return s_params_DeleteADegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteADegree
        {
            public readonly string ADId = "ADId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AzmoonDegreeController : Jazb.Web.Areas.Admin.Controllers.AzmoonDegreeController
    {
        public T4MVC_AzmoonDegreeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            IndexOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ListDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListData(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ListDataOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDegree(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            AddDegreeOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.DomainClasses.Entities.AzmoonDegree model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDegree(Jazb.DomainClasses.Entities.AzmoonDegree model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddDegreeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AZId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditDegree(int AZId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AZId", AZId);
            EditDegreeOverride(callInfo, AZId);
            return callInfo;
        }

        [NonAction]
        partial void EditDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.DomainClasses.Entities.AzmoonDegree model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditDegree(Jazb.DomainClasses.Entities.AzmoonDegree model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditDegreeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteADegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int ADId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteADegree(int ADId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteADegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ADId", ADId);
            DeleteADegreeOverride(callInfo, ADId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
