// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Areas.Admin.Controllers
{
    public partial class AzmoonSettingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AzmoonSettingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAzmoonDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllAzmoonDegrees()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonDegrees);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAzmoonDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpAzmoonDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownAzmoonDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAzmoonEducationSkill()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonEducationSkill);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllAzmoonEducatedSkills()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonEducatedSkills);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAzmooneducatedSkills()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmooneducatedSkills);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAzmoonJob()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonJob);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllAzmoonJobs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonJobs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAzmoonJob()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonJob);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpAzmoonJob()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonJob);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownAzmoonJob()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonJob);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAzmoonPlace()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonPlace);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllAzmoonPlaces()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonPlaces);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAzmoonPlace()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonPlace);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpAzmoonPlace()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonPlace);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownAzmoonPlace()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonPlace);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddDevotionType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDevotionType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllDevotionTypes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotionTypes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDevotionType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDevotionType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpDevotionType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpDevotionType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownDevotionType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownDevotionType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAzmoonQoutaType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonQoutaType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllAzmoonQoutaTypes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonQoutaTypes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAzmoonQoutaType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonQoutaType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpAzmoonQoutaTypee()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonQoutaTypee);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownAzmoonQoutaType()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonQoutaType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowLinks()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowLinks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ActiveAzmoonLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActiveAzmoonLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontActiveAzmoonLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontActiveAzmoonLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowAgahiLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAgahiLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontShowAgahiLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowAgahiLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowRegisterLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowRegisterLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontShowRegisterLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowRegisterLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowViewCardLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewCardLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontShowViewCardLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewCardLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowViewResultLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewResultLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontShowViewResultLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewResultLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowViewEditLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewEditLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DontShowViewEditLink()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewEditLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowAzmoonForUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAzmoonForUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowAzmoonForEveryOne()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAzmoonForEveryOne);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AzmoonSettingController Actions { get { return MVC.Admin.AzmoonSetting; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AzmoonSetting";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AzmoonSetting";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddAzmoonDegree = "AddAzmoonDegree";
            public readonly string GetAllAzmoonDegrees = "GetAllAzmoonDegrees";
            public readonly string DeleteAzmoonDegree = "DeleteAzmoonDegree";
            public readonly string UpAzmoonDegree = "UpAzmoonDegree";
            public readonly string DownAzmoonDegree = "DownAzmoonDegree";
            public readonly string AddAzmoonEducationSkill = "AddAzmoonEducationSkill";
            public readonly string GetAllAzmoonEducatedSkills = "GetAllAzmoonEducatedSkills";
            public readonly string DeleteAzmooneducatedSkills = "DeleteAzmooneducatedSkills";
            public readonly string AddAzmoonJob = "AddAzmoonJob";
            public readonly string GetAllAzmoonJobs = "GetAllAzmoonJobs";
            public readonly string DeleteAzmoonJob = "DeleteAzmoonJob";
            public readonly string UpAzmoonJob = "UpAzmoonJob";
            public readonly string DownAzmoonJob = "DownAzmoonJob";
            public readonly string AddAzmoonPlace = "AddAzmoonPlace";
            public readonly string GetAllAzmoonPlaces = "GetAllAzmoonPlaces";
            public readonly string DeleteAzmoonPlace = "DeleteAzmoonPlace";
            public readonly string UpAzmoonPlace = "UpAzmoonPlace";
            public readonly string DownAzmoonPlace = "DownAzmoonPlace";
            public readonly string AddDevotionType = "AddDevotionType";
            public readonly string GetAllDevotionTypes = "GetAllDevotionTypes";
            public readonly string DeleteDevotionType = "DeleteDevotionType";
            public readonly string UpDevotionType = "UpDevotionType";
            public readonly string DownDevotionType = "DownDevotionType";
            public readonly string AddAzmoonQoutaType = "AddAzmoonQoutaType";
            public readonly string GetAllAzmoonQoutaTypes = "GetAllAzmoonQoutaTypes";
            public readonly string DeleteAzmoonQoutaType = "DeleteAzmoonQoutaType";
            public readonly string UpAzmoonQoutaTypee = "UpAzmoonQoutaTypee";
            public readonly string DownAzmoonQoutaType = "DownAzmoonQoutaType";
            public readonly string ShowLinks = "ShowLinks";
            public readonly string ActiveAzmoonLink = "ActiveAzmoonLink";
            public readonly string DontActiveAzmoonLink = "DontActiveAzmoonLink";
            public readonly string ShowAgahiLink = "ShowAgahiLink";
            public readonly string DontShowAgahiLink = "DontShowAgahiLink";
            public readonly string ShowRegisterLink = "ShowRegisterLink";
            public readonly string DontShowRegisterLink = "DontShowRegisterLink";
            public readonly string ShowViewCardLink = "ShowViewCardLink";
            public readonly string DontShowViewCardLink = "DontShowViewCardLink";
            public readonly string ShowViewResultLink = "ShowViewResultLink";
            public readonly string DontShowViewResultLink = "DontShowViewResultLink";
            public readonly string ShowViewEditLink = "ShowViewEditLink";
            public readonly string DontShowViewEditLink = "DontShowViewEditLink";
            public readonly string ShowAzmoonForUser = "ShowAzmoonForUser";
            public readonly string ShowAzmoonForEveryOne = "ShowAzmoonForEveryOne";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddAzmoonDegree = "AddAzmoonDegree";
            public const string GetAllAzmoonDegrees = "GetAllAzmoonDegrees";
            public const string DeleteAzmoonDegree = "DeleteAzmoonDegree";
            public const string UpAzmoonDegree = "UpAzmoonDegree";
            public const string DownAzmoonDegree = "DownAzmoonDegree";
            public const string AddAzmoonEducationSkill = "AddAzmoonEducationSkill";
            public const string GetAllAzmoonEducatedSkills = "GetAllAzmoonEducatedSkills";
            public const string DeleteAzmooneducatedSkills = "DeleteAzmooneducatedSkills";
            public const string AddAzmoonJob = "AddAzmoonJob";
            public const string GetAllAzmoonJobs = "GetAllAzmoonJobs";
            public const string DeleteAzmoonJob = "DeleteAzmoonJob";
            public const string UpAzmoonJob = "UpAzmoonJob";
            public const string DownAzmoonJob = "DownAzmoonJob";
            public const string AddAzmoonPlace = "AddAzmoonPlace";
            public const string GetAllAzmoonPlaces = "GetAllAzmoonPlaces";
            public const string DeleteAzmoonPlace = "DeleteAzmoonPlace";
            public const string UpAzmoonPlace = "UpAzmoonPlace";
            public const string DownAzmoonPlace = "DownAzmoonPlace";
            public const string AddDevotionType = "AddDevotionType";
            public const string GetAllDevotionTypes = "GetAllDevotionTypes";
            public const string DeleteDevotionType = "DeleteDevotionType";
            public const string UpDevotionType = "UpDevotionType";
            public const string DownDevotionType = "DownDevotionType";
            public const string AddAzmoonQoutaType = "AddAzmoonQoutaType";
            public const string GetAllAzmoonQoutaTypes = "GetAllAzmoonQoutaTypes";
            public const string DeleteAzmoonQoutaType = "DeleteAzmoonQoutaType";
            public const string UpAzmoonQoutaTypee = "UpAzmoonQoutaTypee";
            public const string DownAzmoonQoutaType = "DownAzmoonQoutaType";
            public const string ShowLinks = "ShowLinks";
            public const string ActiveAzmoonLink = "ActiveAzmoonLink";
            public const string DontActiveAzmoonLink = "DontActiveAzmoonLink";
            public const string ShowAgahiLink = "ShowAgahiLink";
            public const string DontShowAgahiLink = "DontShowAgahiLink";
            public const string ShowRegisterLink = "ShowRegisterLink";
            public const string DontShowRegisterLink = "DontShowRegisterLink";
            public const string ShowViewCardLink = "ShowViewCardLink";
            public const string DontShowViewCardLink = "DontShowViewCardLink";
            public const string ShowViewResultLink = "ShowViewResultLink";
            public const string DontShowViewResultLink = "DontShowViewResultLink";
            public const string ShowViewEditLink = "ShowViewEditLink";
            public const string DontShowViewEditLink = "DontShowViewEditLink";
            public const string ShowAzmoonForUser = "ShowAzmoonForUser";
            public const string ShowAzmoonForEveryOne = "ShowAzmoonForEveryOne";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddAzmoonDegree s_params_AddAzmoonDegree = new ActionParamsClass_AddAzmoonDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAzmoonDegree AddAzmoonDegreeParams { get { return s_params_AddAzmoonDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAzmoonDegree
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllAzmoonDegrees s_params_GetAllAzmoonDegrees = new ActionParamsClass_GetAllAzmoonDegrees();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllAzmoonDegrees GetAllAzmoonDegreesParams { get { return s_params_GetAllAzmoonDegrees; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllAzmoonDegrees
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteAzmoonDegree s_params_DeleteAzmoonDegree = new ActionParamsClass_DeleteAzmoonDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAzmoonDegree DeleteAzmoonDegreeParams { get { return s_params_DeleteAzmoonDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAzmoonDegree
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpAzmoonDegree s_params_UpAzmoonDegree = new ActionParamsClass_UpAzmoonDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpAzmoonDegree UpAzmoonDegreeParams { get { return s_params_UpAzmoonDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpAzmoonDegree
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DownAzmoonDegree s_params_DownAzmoonDegree = new ActionParamsClass_DownAzmoonDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownAzmoonDegree DownAzmoonDegreeParams { get { return s_params_DownAzmoonDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownAzmoonDegree
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddAzmoonEducationSkill s_params_AddAzmoonEducationSkill = new ActionParamsClass_AddAzmoonEducationSkill();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAzmoonEducationSkill AddAzmoonEducationSkillParams { get { return s_params_AddAzmoonEducationSkill; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAzmoonEducationSkill
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllAzmoonEducatedSkills s_params_GetAllAzmoonEducatedSkills = new ActionParamsClass_GetAllAzmoonEducatedSkills();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllAzmoonEducatedSkills GetAllAzmoonEducatedSkillsParams { get { return s_params_GetAllAzmoonEducatedSkills; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllAzmoonEducatedSkills
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteAzmooneducatedSkills s_params_DeleteAzmooneducatedSkills = new ActionParamsClass_DeleteAzmooneducatedSkills();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAzmooneducatedSkills DeleteAzmooneducatedSkillsParams { get { return s_params_DeleteAzmooneducatedSkills; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAzmooneducatedSkills
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_AddAzmoonJob s_params_AddAzmoonJob = new ActionParamsClass_AddAzmoonJob();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAzmoonJob AddAzmoonJobParams { get { return s_params_AddAzmoonJob; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAzmoonJob
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllAzmoonJobs s_params_GetAllAzmoonJobs = new ActionParamsClass_GetAllAzmoonJobs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllAzmoonJobs GetAllAzmoonJobsParams { get { return s_params_GetAllAzmoonJobs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllAzmoonJobs
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteAzmoonJob s_params_DeleteAzmoonJob = new ActionParamsClass_DeleteAzmoonJob();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAzmoonJob DeleteAzmoonJobParams { get { return s_params_DeleteAzmoonJob; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAzmoonJob
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpAzmoonJob s_params_UpAzmoonJob = new ActionParamsClass_UpAzmoonJob();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpAzmoonJob UpAzmoonJobParams { get { return s_params_UpAzmoonJob; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpAzmoonJob
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DownAzmoonJob s_params_DownAzmoonJob = new ActionParamsClass_DownAzmoonJob();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownAzmoonJob DownAzmoonJobParams { get { return s_params_DownAzmoonJob; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownAzmoonJob
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddAzmoonPlace s_params_AddAzmoonPlace = new ActionParamsClass_AddAzmoonPlace();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAzmoonPlace AddAzmoonPlaceParams { get { return s_params_AddAzmoonPlace; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAzmoonPlace
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllAzmoonPlaces s_params_GetAllAzmoonPlaces = new ActionParamsClass_GetAllAzmoonPlaces();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllAzmoonPlaces GetAllAzmoonPlacesParams { get { return s_params_GetAllAzmoonPlaces; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllAzmoonPlaces
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteAzmoonPlace s_params_DeleteAzmoonPlace = new ActionParamsClass_DeleteAzmoonPlace();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAzmoonPlace DeleteAzmoonPlaceParams { get { return s_params_DeleteAzmoonPlace; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAzmoonPlace
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpAzmoonPlace s_params_UpAzmoonPlace = new ActionParamsClass_UpAzmoonPlace();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpAzmoonPlace UpAzmoonPlaceParams { get { return s_params_UpAzmoonPlace; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpAzmoonPlace
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DownAzmoonPlace s_params_DownAzmoonPlace = new ActionParamsClass_DownAzmoonPlace();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownAzmoonPlace DownAzmoonPlaceParams { get { return s_params_DownAzmoonPlace; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownAzmoonPlace
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddDevotionType s_params_AddDevotionType = new ActionParamsClass_AddDevotionType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddDevotionType AddDevotionTypeParams { get { return s_params_AddDevotionType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddDevotionType
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllDevotionTypes s_params_GetAllDevotionTypes = new ActionParamsClass_GetAllDevotionTypes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllDevotionTypes GetAllDevotionTypesParams { get { return s_params_GetAllDevotionTypes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllDevotionTypes
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteDevotionType s_params_DeleteDevotionType = new ActionParamsClass_DeleteDevotionType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDevotionType DeleteDevotionTypeParams { get { return s_params_DeleteDevotionType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDevotionType
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpDevotionType s_params_UpDevotionType = new ActionParamsClass_UpDevotionType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpDevotionType UpDevotionTypeParams { get { return s_params_UpDevotionType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpDevotionType
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DownDevotionType s_params_DownDevotionType = new ActionParamsClass_DownDevotionType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownDevotionType DownDevotionTypeParams { get { return s_params_DownDevotionType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownDevotionType
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_AddAzmoonQoutaType s_params_AddAzmoonQoutaType = new ActionParamsClass_AddAzmoonQoutaType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAzmoonQoutaType AddAzmoonQoutaTypeParams { get { return s_params_AddAzmoonQoutaType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAzmoonQoutaType
        {
            public readonly string AId = "AId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetAllAzmoonQoutaTypes s_params_GetAllAzmoonQoutaTypes = new ActionParamsClass_GetAllAzmoonQoutaTypes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllAzmoonQoutaTypes GetAllAzmoonQoutaTypesParams { get { return s_params_GetAllAzmoonQoutaTypes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllAzmoonQoutaTypes
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_DeleteAzmoonQoutaType s_params_DeleteAzmoonQoutaType = new ActionParamsClass_DeleteAzmoonQoutaType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAzmoonQoutaType DeleteAzmoonQoutaTypeParams { get { return s_params_DeleteAzmoonQoutaType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAzmoonQoutaType
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpAzmoonQoutaTypee s_params_UpAzmoonQoutaTypee = new ActionParamsClass_UpAzmoonQoutaTypee();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpAzmoonQoutaTypee UpAzmoonQoutaTypeeParams { get { return s_params_UpAzmoonQoutaTypee; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpAzmoonQoutaTypee
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DownAzmoonQoutaType s_params_DownAzmoonQoutaType = new ActionParamsClass_DownAzmoonQoutaType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownAzmoonQoutaType DownAzmoonQoutaTypeParams { get { return s_params_DownAzmoonQoutaType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownAzmoonQoutaType
        {
            public readonly string Id = "Id";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ShowLinks s_params_ShowLinks = new ActionParamsClass_ShowLinks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowLinks ShowLinksParams { get { return s_params_ShowLinks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowLinks
        {
            public readonly string AId = "AId";
        }
        static readonly ActionParamsClass_ActiveAzmoonLink s_params_ActiveAzmoonLink = new ActionParamsClass_ActiveAzmoonLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActiveAzmoonLink ActiveAzmoonLinkParams { get { return s_params_ActiveAzmoonLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActiveAzmoonLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontActiveAzmoonLink s_params_DontActiveAzmoonLink = new ActionParamsClass_DontActiveAzmoonLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontActiveAzmoonLink DontActiveAzmoonLinkParams { get { return s_params_DontActiveAzmoonLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontActiveAzmoonLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowAgahiLink s_params_ShowAgahiLink = new ActionParamsClass_ShowAgahiLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowAgahiLink ShowAgahiLinkParams { get { return s_params_ShowAgahiLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowAgahiLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontShowAgahiLink s_params_DontShowAgahiLink = new ActionParamsClass_DontShowAgahiLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontShowAgahiLink DontShowAgahiLinkParams { get { return s_params_DontShowAgahiLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontShowAgahiLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowRegisterLink s_params_ShowRegisterLink = new ActionParamsClass_ShowRegisterLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowRegisterLink ShowRegisterLinkParams { get { return s_params_ShowRegisterLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowRegisterLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontShowRegisterLink s_params_DontShowRegisterLink = new ActionParamsClass_DontShowRegisterLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontShowRegisterLink DontShowRegisterLinkParams { get { return s_params_DontShowRegisterLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontShowRegisterLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowViewCardLink s_params_ShowViewCardLink = new ActionParamsClass_ShowViewCardLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowViewCardLink ShowViewCardLinkParams { get { return s_params_ShowViewCardLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowViewCardLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontShowViewCardLink s_params_DontShowViewCardLink = new ActionParamsClass_DontShowViewCardLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontShowViewCardLink DontShowViewCardLinkParams { get { return s_params_DontShowViewCardLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontShowViewCardLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowViewResultLink s_params_ShowViewResultLink = new ActionParamsClass_ShowViewResultLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowViewResultLink ShowViewResultLinkParams { get { return s_params_ShowViewResultLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowViewResultLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontShowViewResultLink s_params_DontShowViewResultLink = new ActionParamsClass_DontShowViewResultLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontShowViewResultLink DontShowViewResultLinkParams { get { return s_params_DontShowViewResultLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontShowViewResultLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowViewEditLink s_params_ShowViewEditLink = new ActionParamsClass_ShowViewEditLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowViewEditLink ShowViewEditLinkParams { get { return s_params_ShowViewEditLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowViewEditLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_DontShowViewEditLink s_params_DontShowViewEditLink = new ActionParamsClass_DontShowViewEditLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DontShowViewEditLink DontShowViewEditLinkParams { get { return s_params_DontShowViewEditLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DontShowViewEditLink
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowAzmoonForUser s_params_ShowAzmoonForUser = new ActionParamsClass_ShowAzmoonForUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowAzmoonForUser ShowAzmoonForUserParams { get { return s_params_ShowAzmoonForUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowAzmoonForUser
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowAzmoonForEveryOne s_params_ShowAzmoonForEveryOne = new ActionParamsClass_ShowAzmoonForEveryOne();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowAzmoonForEveryOne ShowAzmoonForEveryOneParams { get { return s_params_ShowAzmoonForEveryOne; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowAzmoonForEveryOne
        {
            public readonly string AID = "AID";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AddAzmoonDegree = "_AddAzmoonDegree";
                public readonly string _AddAzmoonEducationSkill = "_AddAzmoonEducationSkill";
                public readonly string _AddAzmoonJob = "_AddAzmoonJob";
                public readonly string _AddAzmoonPlace = "_AddAzmoonPlace";
                public readonly string _AddAzmoonQoutaType = "_AddAzmoonQoutaType";
                public readonly string _AddDevotionType = "_AddDevotionType";
                public readonly string _GetAllAzmoonDegrees = "_GetAllAzmoonDegrees";
                public readonly string _GetAllAzmoonEducatedSkills = "_GetAllAzmoonEducatedSkills";
                public readonly string _GetAllAzmoonJobs = "_GetAllAzmoonJobs";
                public readonly string _GetAllAzmoonPlaces = "_GetAllAzmoonPlaces";
                public readonly string _GetAllAzmoonQoutaTypes = "_GetAllAzmoonQoutaTypes";
                public readonly string _GetAllDevotionTypes = "_GetAllDevotionTypes";
                public readonly string _Index = "_Index";
                public readonly string _ManageAzmoonDegree = "_ManageAzmoonDegree";
                public readonly string _ShowLinks = "_ShowLinks";
            }
            public readonly string _AddAzmoonDegree = "~/Areas/Admin/Views/AzmoonSetting/_AddAzmoonDegree.cshtml";
            public readonly string _AddAzmoonEducationSkill = "~/Areas/Admin/Views/AzmoonSetting/_AddAzmoonEducationSkill.cshtml";
            public readonly string _AddAzmoonJob = "~/Areas/Admin/Views/AzmoonSetting/_AddAzmoonJob.cshtml";
            public readonly string _AddAzmoonPlace = "~/Areas/Admin/Views/AzmoonSetting/_AddAzmoonPlace.cshtml";
            public readonly string _AddAzmoonQoutaType = "~/Areas/Admin/Views/AzmoonSetting/_AddAzmoonQoutaType.cshtml";
            public readonly string _AddDevotionType = "~/Areas/Admin/Views/AzmoonSetting/_AddDevotionType.cshtml";
            public readonly string _GetAllAzmoonDegrees = "~/Areas/Admin/Views/AzmoonSetting/_GetAllAzmoonDegrees.cshtml";
            public readonly string _GetAllAzmoonEducatedSkills = "~/Areas/Admin/Views/AzmoonSetting/_GetAllAzmoonEducatedSkills.cshtml";
            public readonly string _GetAllAzmoonJobs = "~/Areas/Admin/Views/AzmoonSetting/_GetAllAzmoonJobs.cshtml";
            public readonly string _GetAllAzmoonPlaces = "~/Areas/Admin/Views/AzmoonSetting/_GetAllAzmoonPlaces.cshtml";
            public readonly string _GetAllAzmoonQoutaTypes = "~/Areas/Admin/Views/AzmoonSetting/_GetAllAzmoonQoutaTypes.cshtml";
            public readonly string _GetAllDevotionTypes = "~/Areas/Admin/Views/AzmoonSetting/_GetAllDevotionTypes.cshtml";
            public readonly string _Index = "~/Areas/Admin/Views/AzmoonSetting/_Index.cshtml";
            public readonly string _ManageAzmoonDegree = "~/Areas/Admin/Views/AzmoonSetting/_ManageAzmoonDegree.cshtml";
            public readonly string _ShowLinks = "~/Areas/Admin/Views/AzmoonSetting/_ShowLinks.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AzmoonSettingController : Jazb.Web.Areas.Admin.Controllers.AzmoonSettingController
    {
        public T4MVC_AzmoonSettingController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            IndexOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonDegree(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddAzmoonDegreeOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.AzmoonDegreeModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonDegree(Jazb.Model.AdminModel.ManageAzmoon.AzmoonDegreeModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAzmoonDegreeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllAzmoonDegreesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllAzmoonDegrees(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonDegrees);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllAzmoonDegreesOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAzmoonDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAzmoonDegree(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteAzmoonDegreeOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpAzmoonDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpAzmoonDegree(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            UpAzmoonDegreeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DownAzmoonDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownAzmoonDegree(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            DownAzmoonDegreeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonEducationSkillOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonEducationSkill(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonEducationSkill);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddAzmoonEducationSkillOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonEducationSkillOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.AzmoonEducationViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonEducationSkill(Jazb.Model.AdminModel.ManageAzmoon.AzmoonEducationViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonEducationSkill);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAzmoonEducationSkillOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllAzmoonEducatedSkillsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllAzmoonEducatedSkills(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonEducatedSkills);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllAzmoonEducatedSkillsOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAzmooneducatedSkillsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAzmooneducatedSkills(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmooneducatedSkills);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteAzmooneducatedSkillsOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonJobOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonJob(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonJob);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddAzmoonJobOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonJobOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.AzmoonJobModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonJob(Jazb.Model.AdminModel.ManageAzmoon.AzmoonJobModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonJob);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAzmoonJobOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllAzmoonJobsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllAzmoonJobs(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonJobs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllAzmoonJobsOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAzmoonJobOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAzmoonJob(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonJob);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteAzmoonJobOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpAzmoonJobOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpAzmoonJob(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonJob);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            UpAzmoonJobOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DownAzmoonJobOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownAzmoonJob(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonJob);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            DownAzmoonJobOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonPlaceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonPlace(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonPlace);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddAzmoonPlaceOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonPlaceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.AzmoonPlaceModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonPlace(Jazb.Model.AdminModel.ManageAzmoon.AzmoonPlaceModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonPlace);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAzmoonPlaceOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllAzmoonPlacesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllAzmoonPlaces(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonPlaces);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllAzmoonPlacesOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAzmoonPlaceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAzmoonPlace(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonPlace);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteAzmoonPlaceOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpAzmoonPlaceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpAzmoonPlace(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonPlace);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            UpAzmoonPlaceOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DownAzmoonPlaceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownAzmoonPlace(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonPlace);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            DownAzmoonPlaceOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddDevotionTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDevotionType(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDevotionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddDevotionTypeOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddDevotionTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.DevotionTypeModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDevotionType(Jazb.Model.AdminModel.ManageAzmoon.DevotionTypeModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDevotionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddDevotionTypeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllDevotionTypesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllDevotionTypes(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotionTypes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllDevotionTypesOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDevotionTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDevotionType(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDevotionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteDevotionTypeOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpDevotionTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpDevotionType(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpDevotionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            UpDevotionTypeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DownDevotionTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownDevotionType(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownDevotionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            DownDevotionTypeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonQoutaTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonQoutaType(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonQoutaType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            AddAzmoonQoutaTypeOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void AddAzmoonQoutaTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.ManageAzmoon.AzmoonQoutaTypeModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAzmoonQoutaType(Jazb.Model.AdminModel.ManageAzmoon.AzmoonQoutaTypeModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAzmoonQoutaType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAzmoonQoutaTypeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetAllAzmoonQoutaTypesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllAzmoonQoutaTypes(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllAzmoonQoutaTypes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            GetAllAzmoonQoutaTypesOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAzmoonQoutaTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAzmoonQoutaType(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAzmoonQoutaType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteAzmoonQoutaTypeOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpAzmoonQoutaTypeeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpAzmoonQoutaTypee(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpAzmoonQoutaTypee);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            UpAzmoonQoutaTypeeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DownAzmoonQoutaTypeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownAzmoonQoutaType(int Id, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownAzmoonQoutaType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            DownAzmoonQoutaTypeOverride(callInfo, Id, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ShowLinksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowLinks(int AId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowLinks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AId", AId);
            ShowLinksOverride(callInfo, AId);
            return callInfo;
        }

        [NonAction]
        partial void ActiveAzmoonLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActiveAzmoonLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActiveAzmoonLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ActiveAzmoonLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontActiveAzmoonLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontActiveAzmoonLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontActiveAzmoonLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontActiveAzmoonLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowAgahiLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowAgahiLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAgahiLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowAgahiLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontShowAgahiLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontShowAgahiLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowAgahiLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontShowAgahiLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowRegisterLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowRegisterLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowRegisterLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowRegisterLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontShowRegisterLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontShowRegisterLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowRegisterLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontShowRegisterLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowViewCardLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowViewCardLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewCardLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowViewCardLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontShowViewCardLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontShowViewCardLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewCardLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontShowViewCardLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowViewResultLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowViewResultLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewResultLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowViewResultLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontShowViewResultLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontShowViewResultLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewResultLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontShowViewResultLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowViewEditLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowViewEditLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowViewEditLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowViewEditLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void DontShowViewEditLinkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontShowViewEditLink(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontShowViewEditLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            DontShowViewEditLinkOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowAzmoonForUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowAzmoonForUser(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAzmoonForUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowAzmoonForUserOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ShowAzmoonForEveryOneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowAzmoonForEveryOne(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAzmoonForEveryOne);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ShowAzmoonForEveryOneOverride(callInfo, AID);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
