// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Areas.Admin.Controllers
{
    public partial class ContactUsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ContactUsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Detail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetByAzmoonId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetByAzmoonId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetNoneAnswerByAzmoonId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetNoneAnswerByAzmoonId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAnswerByAzmoonId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAnswerByAzmoonId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NextFaqs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NextFaqs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PreviuseFaqs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PreviuseFaqs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ContactUsController Actions { get { return MVC.Admin.ContactUs; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ContactUs";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ContactUs";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Detail = "Detail";
            public readonly string GetByAzmoonId = "GetByAzmoonId";
            public readonly string GetNoneAnswerByAzmoonId = "GetNoneAnswerByAzmoonId";
            public readonly string GetAnswerByAzmoonId = "GetAnswerByAzmoonId";
            public readonly string NextFaqs = "NextFaqs";
            public readonly string PreviuseFaqs = "PreviuseFaqs";
            public readonly string SaveDate = "SaveDate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Detail = "Detail";
            public const string GetByAzmoonId = "GetByAzmoonId";
            public const string GetNoneAnswerByAzmoonId = "GetNoneAnswerByAzmoonId";
            public const string GetAnswerByAzmoonId = "GetAnswerByAzmoonId";
            public const string NextFaqs = "NextFaqs";
            public const string PreviuseFaqs = "PreviuseFaqs";
            public const string SaveDate = "SaveDate";
        }


        static readonly ActionParamsClass_Detail s_params_Detail = new ActionParamsClass_Detail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Detail DetailParams { get { return s_params_Detail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Detail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetByAzmoonId s_params_GetByAzmoonId = new ActionParamsClass_GetByAzmoonId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetByAzmoonId GetByAzmoonIdParams { get { return s_params_GetByAzmoonId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetByAzmoonId
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_GetNoneAnswerByAzmoonId s_params_GetNoneAnswerByAzmoonId = new ActionParamsClass_GetNoneAnswerByAzmoonId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetNoneAnswerByAzmoonId GetNoneAnswerByAzmoonIdParams { get { return s_params_GetNoneAnswerByAzmoonId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetNoneAnswerByAzmoonId
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_GetAnswerByAzmoonId s_params_GetAnswerByAzmoonId = new ActionParamsClass_GetAnswerByAzmoonId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAnswerByAzmoonId GetAnswerByAzmoonIdParams { get { return s_params_GetAnswerByAzmoonId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAnswerByAzmoonId
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_NextFaqs s_params_NextFaqs = new ActionParamsClass_NextFaqs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NextFaqs NextFaqsParams { get { return s_params_NextFaqs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NextFaqs
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PreviuseFaqs s_params_PreviuseFaqs = new ActionParamsClass_PreviuseFaqs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PreviuseFaqs PreviuseFaqsParams { get { return s_params_PreviuseFaqs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PreviuseFaqs
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SaveDate s_params_SaveDate = new ActionParamsClass_SaveDate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDate SaveDateParams { get { return s_params_SaveDate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDate
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AllAnswerd = "_AllAnswerd";
                public readonly string _Detail = "_Detail";
                public readonly string _Index = "_Index";
                public readonly string _noneAnswer = "_noneAnswer";
            }
            public readonly string _AllAnswerd = "~/Areas/Admin/Views/ContactUs/_AllAnswerd.cshtml";
            public readonly string _Detail = "~/Areas/Admin/Views/ContactUs/_Detail.cshtml";
            public readonly string _Index = "~/Areas/Admin/Views/ContactUs/_Index.cshtml";
            public readonly string _noneAnswer = "~/Areas/Admin/Views/ContactUs/_noneAnswer.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ContactUsController : Jazb.Web.Areas.Admin.Controllers.ContactUsController
    {
        public T4MVC_ContactUsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Detail(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetByAzmoonIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetByAzmoonId(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetByAzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            GetByAzmoonIdOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void GetNoneAnswerByAzmoonIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetNoneAnswerByAzmoonId(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetNoneAnswerByAzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            GetNoneAnswerByAzmoonIdOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void GetAnswerByAzmoonIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAnswerByAzmoonId(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAnswerByAzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            GetAnswerByAzmoonIdOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void NextFaqsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult NextFaqs(int AzmoonId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NextFaqs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NextFaqsOverride(callInfo, AzmoonId, id);
            return callInfo;
        }

        [NonAction]
        partial void PreviuseFaqsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PreviuseFaqs(int AzmoonId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PreviuseFaqs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PreviuseFaqsOverride(callInfo, AzmoonId, id);
            return callInfo;
        }

        [NonAction]
        partial void SaveDateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.DomainClasses.Entities.FAQ model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDate(Jazb.DomainClasses.Entities.FAQ model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveDateOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
