// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Areas.Admin.Controllers
{
    public partial class ValeantearreportsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ValeantearreportsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllDevotion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllDevotionByGender()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotionByGender);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllValentearGroupBy()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllValentearGroupBy);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllPasokhnamehValentearView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllPasokhnamehValentearView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllCardValentearView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCardValentearView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllChairNumberValentear()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllChairNumberValentear);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllValentearGroupByGender()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllValentearGroupByGender);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValentearFullExport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearFullExport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValentearFullWithNumberExport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearFullWithNumberExport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SavePicturesValentera()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SavePicturesValentera);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValentearAcceptExport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearAcceptExport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ValentearAnswerFinalExport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearAnswerFinalExport);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ValeantearreportsController Actions { get { return MVC.Admin.Valeantearreports; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Valeantearreports";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Valeantearreports";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetAllDevotion = "GetAllDevotion";
            public readonly string LoadReportSnapshot = "LoadReportSnapshot";
            public readonly string GetAllDevotionByGender = "GetAllDevotionByGender";
            public readonly string LoadReportSnapshotByGender = "LoadReportSnapshotByGender";
            public readonly string GetAllValentearGroupBy = "GetAllValentearGroupBy";
            public readonly string LoadReportValentearGroupBy = "LoadReportValentearGroupBy";
            public readonly string GetAllPasokhnamehValentearView = "GetAllPasokhnamehValentearView";
            public readonly string LoadReportPasokhnamehValentear = "LoadReportPasokhnamehValentear";
            public readonly string GetAllCardValentearView = "GetAllCardValentearView";
            public readonly string LoadReportCardValentear = "LoadReportCardValentear";
            public readonly string GetAllChairNumberValentear = "GetAllChairNumberValentear";
            public readonly string LoadReportChairNumberValentear = "LoadReportChairNumberValentear";
            public readonly string GetAllValentearGroupByGender = "GetAllValentearGroupByGender";
            public readonly string LoadReportValentearGroupByGender = "LoadReportValentearGroupByGender";
            public readonly string ValentearFullExport = "ValentearFullExport";
            public readonly string ValentearFullWithNumberExport = "ValentearFullWithNumberExport";
            public readonly string SavePicturesValentera = "SavePicturesValentera";
            public readonly string ValentearAcceptExport = "ValentearAcceptExport";
            public readonly string ValentearAnswerFinalExport = "ValentearAnswerFinalExport";
            public readonly string ViewerEvent = "ViewerEvent";
            public readonly string PrintReport = "PrintReport";
            public readonly string ExportReport = "ExportReport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetAllDevotion = "GetAllDevotion";
            public const string LoadReportSnapshot = "LoadReportSnapshot";
            public const string GetAllDevotionByGender = "GetAllDevotionByGender";
            public const string LoadReportSnapshotByGender = "LoadReportSnapshotByGender";
            public const string GetAllValentearGroupBy = "GetAllValentearGroupBy";
            public const string LoadReportValentearGroupBy = "LoadReportValentearGroupBy";
            public const string GetAllPasokhnamehValentearView = "GetAllPasokhnamehValentearView";
            public const string LoadReportPasokhnamehValentear = "LoadReportPasokhnamehValentear";
            public const string GetAllCardValentearView = "GetAllCardValentearView";
            public const string LoadReportCardValentear = "LoadReportCardValentear";
            public const string GetAllChairNumberValentear = "GetAllChairNumberValentear";
            public const string LoadReportChairNumberValentear = "LoadReportChairNumberValentear";
            public const string GetAllValentearGroupByGender = "GetAllValentearGroupByGender";
            public const string LoadReportValentearGroupByGender = "LoadReportValentearGroupByGender";
            public const string ValentearFullExport = "ValentearFullExport";
            public const string ValentearFullWithNumberExport = "ValentearFullWithNumberExport";
            public const string SavePicturesValentera = "SavePicturesValentera";
            public const string ValentearAcceptExport = "ValentearAcceptExport";
            public const string ValentearAnswerFinalExport = "ValentearAnswerFinalExport";
            public const string ViewerEvent = "ViewerEvent";
            public const string PrintReport = "PrintReport";
            public const string ExportReport = "ExportReport";
        }


        static readonly ActionParamsClass_GetAllDevotion s_params_GetAllDevotion = new ActionParamsClass_GetAllDevotion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllDevotion GetAllDevotionParams { get { return s_params_GetAllDevotion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllDevotion
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllDevotionByGender s_params_GetAllDevotionByGender = new ActionParamsClass_GetAllDevotionByGender();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllDevotionByGender GetAllDevotionByGenderParams { get { return s_params_GetAllDevotionByGender; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllDevotionByGender
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllValentearGroupBy s_params_GetAllValentearGroupBy = new ActionParamsClass_GetAllValentearGroupBy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllValentearGroupBy GetAllValentearGroupByParams { get { return s_params_GetAllValentearGroupBy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllValentearGroupBy
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllPasokhnamehValentearView s_params_GetAllPasokhnamehValentearView = new ActionParamsClass_GetAllPasokhnamehValentearView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllPasokhnamehValentearView GetAllPasokhnamehValentearViewParams { get { return s_params_GetAllPasokhnamehValentearView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllPasokhnamehValentearView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllCardValentearView s_params_GetAllCardValentearView = new ActionParamsClass_GetAllCardValentearView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllCardValentearView GetAllCardValentearViewParams { get { return s_params_GetAllCardValentearView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllCardValentearView
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllChairNumberValentear s_params_GetAllChairNumberValentear = new ActionParamsClass_GetAllChairNumberValentear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllChairNumberValentear GetAllChairNumberValentearParams { get { return s_params_GetAllChairNumberValentear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllChairNumberValentear
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetAllValentearGroupByGender s_params_GetAllValentearGroupByGender = new ActionParamsClass_GetAllValentearGroupByGender();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllValentearGroupByGender GetAllValentearGroupByGenderParams { get { return s_params_GetAllValentearGroupByGender; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllValentearGroupByGender
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ValentearFullExport s_params_ValentearFullExport = new ActionParamsClass_ValentearFullExport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValentearFullExport ValentearFullExportParams { get { return s_params_ValentearFullExport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValentearFullExport
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ValentearFullWithNumberExport s_params_ValentearFullWithNumberExport = new ActionParamsClass_ValentearFullWithNumberExport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValentearFullWithNumberExport ValentearFullWithNumberExportParams { get { return s_params_ValentearFullWithNumberExport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValentearFullWithNumberExport
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_SavePicturesValentera s_params_SavePicturesValentera = new ActionParamsClass_SavePicturesValentera();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SavePicturesValentera SavePicturesValenteraParams { get { return s_params_SavePicturesValentera; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SavePicturesValentera
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ValentearAcceptExport s_params_ValentearAcceptExport = new ActionParamsClass_ValentearAcceptExport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValentearAcceptExport ValentearAcceptExportParams { get { return s_params_ValentearAcceptExport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValentearAcceptExport
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ValentearAnswerFinalExport s_params_ValentearAnswerFinalExport = new ActionParamsClass_ValentearAnswerFinalExport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValentearAnswerFinalExport ValentearAnswerFinalExportParams { get { return s_params_ValentearAnswerFinalExport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValentearAnswerFinalExport
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string Grade = "Grade";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GetAllCardValentearView = "GetAllCardValentearView";
                public readonly string GetAllChairNumberValentear = "GetAllChairNumberValentear";
                public readonly string GetAllDevotion = "GetAllDevotion";
                public readonly string GetAllDevotionByGender = "GetAllDevotionByGender";
                public readonly string GetAllPasokhnamehValentearView = "GetAllPasokhnamehValentearView";
                public readonly string GetAllValentearGroupBy = "GetAllValentearGroupBy";
                public readonly string GetAllValentearGroupByGender = "GetAllValentearGroupByGender";
            }
            public readonly string GetAllCardValentearView = "~/Areas/Admin/Views/Valeantearreports/GetAllCardValentearView.cshtml";
            public readonly string GetAllChairNumberValentear = "~/Areas/Admin/Views/Valeantearreports/GetAllChairNumberValentear.cshtml";
            public readonly string GetAllDevotion = "~/Areas/Admin/Views/Valeantearreports/GetAllDevotion.cshtml";
            public readonly string GetAllDevotionByGender = "~/Areas/Admin/Views/Valeantearreports/GetAllDevotionByGender.cshtml";
            public readonly string GetAllPasokhnamehValentearView = "~/Areas/Admin/Views/Valeantearreports/GetAllPasokhnamehValentearView.cshtml";
            public readonly string GetAllValentearGroupBy = "~/Areas/Admin/Views/Valeantearreports/GetAllValentearGroupBy.cshtml";
            public readonly string GetAllValentearGroupByGender = "~/Areas/Admin/Views/Valeantearreports/GetAllValentearGroupByGender.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ValeantearreportsController : Jazb.Web.Areas.Admin.Controllers.ValeantearreportsController
    {
        public T4MVC_ValeantearreportsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetAllDevotionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllDevotion(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllDevotionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportSnapshotOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportSnapshot()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportSnapshot);
            LoadReportSnapshotOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllDevotionByGenderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllDevotionByGender(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllDevotionByGender);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllDevotionByGenderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportSnapshotByGenderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportSnapshotByGender()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportSnapshotByGender);
            LoadReportSnapshotByGenderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllValentearGroupByOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllValentearGroupBy(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllValentearGroupBy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllValentearGroupByOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportValentearGroupByOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportValentearGroupBy()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportValentearGroupBy);
            LoadReportValentearGroupByOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllPasokhnamehValentearViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllPasokhnamehValentearView(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllPasokhnamehValentearView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllPasokhnamehValentearViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportPasokhnamehValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportPasokhnamehValentear()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportPasokhnamehValentear);
            LoadReportPasokhnamehValentearOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllCardValentearViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllCardValentearView(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCardValentearView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllCardValentearViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportCardValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportCardValentear()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportCardValentear);
            LoadReportCardValentearOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllChairNumberValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllChairNumberValentear(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllChairNumberValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllChairNumberValentearOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportChairNumberValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportChairNumberValentear()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportChairNumberValentear);
            LoadReportChairNumberValentearOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllValentearGroupByGenderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllValentearGroupByGender(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllValentearGroupByGender);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllValentearGroupByGenderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LoadReportValentearGroupByGenderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadReportValentearGroupByGender()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadReportValentearGroupByGender);
            LoadReportValentearGroupByGenderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ValentearFullExportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValentearFullExport(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearFullExport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ValentearFullExportOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ValentearFullWithNumberExportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValentearFullWithNumberExport(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearFullWithNumberExport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ValentearFullWithNumberExportOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void SavePicturesValenteraOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SavePicturesValentera(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SavePicturesValentera);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            SavePicturesValenteraOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ValentearAcceptExportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValentearAcceptExport(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearAcceptExport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ValentearAcceptExportOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ValentearAnswerFinalExportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, int Grade);

        [NonAction]
        public override System.Web.Mvc.ActionResult ValentearAnswerFinalExport(int AzmoonId, int Grade)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ValentearAnswerFinalExport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Grade", Grade);
            ValentearAnswerFinalExportOverride(callInfo, AzmoonId, Grade);
            return callInfo;
        }

        [NonAction]
        partial void ViewerEventOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewerEvent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewerEvent);
            ViewerEventOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrintReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintReport);
            PrintReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExportReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportReport);
            ExportReportOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
