// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Areas.Admin.Controllers
{
    public partial class ValentearController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ValentearController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateChairNumber()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateChairNumber);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetDataTableByAzmoon()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDataTableByAzmoon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditSahmiyeh()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSahmiyeh);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AutoCompleteSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AutoCompleteSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BlockValentear()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BlockValentear);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StatusAcceptValentear()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StatusAcceptValentear);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintDataByMelicode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDataByMelicode);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportValentear()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentear);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportSepratJobCity()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportSepratJobCity);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportSepratJobCitySortByAghi()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportSepratJobCitySortByAghi);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportValentearByAgahi()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearByAgahi);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportValentearFillterGendederByAgahi()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearFillterGendederByAgahi);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportValentearChairCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearChairCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetFishPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFishPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetTargPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTargPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPicPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPicPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetLocationRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetLocationRequest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ValentearController Actions { get { return MVC.Admin.Valentear; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Valentear";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Valentear";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Updateamount = "Updateamount";
            public readonly string Index = "Index";
            public readonly string Search = "Search";
            public readonly string CreateChairNumber = "CreateChairNumber";
            public readonly string DataTable = "DataTable";
            public readonly string GetDataTableByAzmoon = "GetDataTableByAzmoon";
            public readonly string Edit = "Edit";
            public readonly string SaveDate = "SaveDate";
            public readonly string EditNOID = "EditNOID";
            public readonly string EditSahmiyeh = "EditSahmiyeh";
            public readonly string AutoCompleteSearch = "AutoCompleteSearch";
            public readonly string BlockValentear = "BlockValentear";
            public readonly string StatusAcceptValentear = "StatusAcceptValentear";
            public readonly string PrintData = "PrintData";
            public readonly string PrintDataByMelicode = "PrintDataByMelicode";
            public readonly string ReportValentear = "ReportValentear";
            public readonly string ReportSepratJobCity = "ReportSepratJobCity";
            public readonly string ReportSepratJobCitySortByAghi = "ReportSepratJobCitySortByAghi";
            public readonly string ReportValentearByAgahi = "ReportValentearByAgahi";
            public readonly string ReportValentearFillterGendederByAgahi = "ReportValentearFillterGendederByAgahi";
            public readonly string ReportValentearChairCard = "ReportValentearChairCard";
            public readonly string GetFishPicture = "GetFishPicture";
            public readonly string GetTargPicture = "GetTargPicture";
            public readonly string GetPicPicture = "GetPicPicture";
            public readonly string GetLocationRequest = "GetLocationRequest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Updateamount = "Updateamount";
            public const string Index = "Index";
            public const string Search = "Search";
            public const string CreateChairNumber = "CreateChairNumber";
            public const string DataTable = "DataTable";
            public const string GetDataTableByAzmoon = "GetDataTableByAzmoon";
            public const string Edit = "Edit";
            public const string SaveDate = "SaveDate";
            public const string EditNOID = "EditNOID";
            public const string EditSahmiyeh = "EditSahmiyeh";
            public const string AutoCompleteSearch = "AutoCompleteSearch";
            public const string BlockValentear = "BlockValentear";
            public const string StatusAcceptValentear = "StatusAcceptValentear";
            public const string PrintData = "PrintData";
            public const string PrintDataByMelicode = "PrintDataByMelicode";
            public const string ReportValentear = "ReportValentear";
            public const string ReportSepratJobCity = "ReportSepratJobCity";
            public const string ReportSepratJobCitySortByAghi = "ReportSepratJobCitySortByAghi";
            public const string ReportValentearByAgahi = "ReportValentearByAgahi";
            public const string ReportValentearFillterGendederByAgahi = "ReportValentearFillterGendederByAgahi";
            public const string ReportValentearChairCard = "ReportValentearChairCard";
            public const string GetFishPicture = "GetFishPicture";
            public const string GetTargPicture = "GetTargPicture";
            public const string GetPicPicture = "GetPicPicture";
            public const string GetLocationRequest = "GetLocationRequest";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_CreateChairNumber s_params_CreateChairNumber = new ActionParamsClass_CreateChairNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateChairNumber CreateChairNumberParams { get { return s_params_CreateChairNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateChairNumber
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_DataTable s_params_DataTable = new ActionParamsClass_DataTable();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataTable DataTableParams { get { return s_params_DataTable; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataTable
        {
            public readonly string term = "term";
            public readonly string page = "page";
            public readonly string count = "count";
            public readonly string searchBy = "searchBy";
        }
        static readonly ActionParamsClass_GetDataTableByAzmoon s_params_GetDataTableByAzmoon = new ActionParamsClass_GetDataTableByAzmoon();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDataTableByAzmoon GetDataTableByAzmoonParams { get { return s_params_GetDataTableByAzmoon; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDataTableByAzmoon
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string term = "term";
            public readonly string page = "page";
            public readonly string count = "count";
            public readonly string searchBy = "searchBy";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string NationalId = "NationalId";
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_SaveDate s_params_SaveDate = new ActionParamsClass_SaveDate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDate SaveDateParams { get { return s_params_SaveDate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDate
        {
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_EditSahmiyeh s_params_EditSahmiyeh = new ActionParamsClass_EditSahmiyeh();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditSahmiyeh EditSahmiyehParams { get { return s_params_EditSahmiyeh; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditSahmiyeh
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string NationalId = "NationalId";
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_AutoCompleteSearch s_params_AutoCompleteSearch = new ActionParamsClass_AutoCompleteSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AutoCompleteSearch AutoCompleteSearchParams { get { return s_params_AutoCompleteSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AutoCompleteSearch
        {
            public readonly string term = "term";
            public readonly string searchBy = "searchBy";
        }
        static readonly ActionParamsClass_BlockValentear s_params_BlockValentear = new ActionParamsClass_BlockValentear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BlockValentear BlockValentearParams { get { return s_params_BlockValentear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BlockValentear
        {
            public readonly string vid = "vid";
            public readonly string term1 = "term1";
            public readonly string page1 = "page1";
            public readonly string count1 = "count1";
            public readonly string searchBy1 = "searchBy1";
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_StatusAcceptValentear s_params_StatusAcceptValentear = new ActionParamsClass_StatusAcceptValentear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StatusAcceptValentear StatusAcceptValentearParams { get { return s_params_StatusAcceptValentear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StatusAcceptValentear
        {
            public readonly string ValentearId = "ValentearId";
            public readonly string AcceptStatus = "AcceptStatus";
            public readonly string Message = "Message";
        }
        static readonly ActionParamsClass_PrintDataByMelicode s_params_PrintDataByMelicode = new ActionParamsClass_PrintDataByMelicode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintDataByMelicode PrintDataByMelicodeParams { get { return s_params_PrintDataByMelicode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintDataByMelicode
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string natinalId = "natinalId";
        }
        static readonly ActionParamsClass_ReportValentear s_params_ReportValentear = new ActionParamsClass_ReportValentear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportValentear ReportValentearParams { get { return s_params_ReportValentear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportValentear
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ReportSepratJobCity s_params_ReportSepratJobCity = new ActionParamsClass_ReportSepratJobCity();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportSepratJobCity ReportSepratJobCityParams { get { return s_params_ReportSepratJobCity; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportSepratJobCity
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ReportSepratJobCitySortByAghi s_params_ReportSepratJobCitySortByAghi = new ActionParamsClass_ReportSepratJobCitySortByAghi();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportSepratJobCitySortByAghi ReportSepratJobCitySortByAghiParams { get { return s_params_ReportSepratJobCitySortByAghi; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportSepratJobCitySortByAghi
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ReportValentearByAgahi s_params_ReportValentearByAgahi = new ActionParamsClass_ReportValentearByAgahi();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportValentearByAgahi ReportValentearByAgahiParams { get { return s_params_ReportValentearByAgahi; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportValentearByAgahi
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ReportValentearFillterGendederByAgahi s_params_ReportValentearFillterGendederByAgahi = new ActionParamsClass_ReportValentearFillterGendederByAgahi();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportValentearFillterGendederByAgahi ReportValentearFillterGendederByAgahiParams { get { return s_params_ReportValentearFillterGendederByAgahi; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportValentearFillterGendederByAgahi
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_ReportValentearChairCard s_params_ReportValentearChairCard = new ActionParamsClass_ReportValentearChairCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportValentearChairCard ReportValentearChairCardParams { get { return s_params_ReportValentearChairCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportValentearChairCard
        {
            public readonly string AzmoonId = "AzmoonId";
        }
        static readonly ActionParamsClass_GetFishPicture s_params_GetFishPicture = new ActionParamsClass_GetFishPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFishPicture GetFishPictureParams { get { return s_params_GetFishPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFishPicture
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string natinalId = "natinalId";
        }
        static readonly ActionParamsClass_GetTargPicture s_params_GetTargPicture = new ActionParamsClass_GetTargPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTargPicture GetTargPictureParams { get { return s_params_GetTargPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTargPicture
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string natinalId = "natinalId";
        }
        static readonly ActionParamsClass_GetPicPicture s_params_GetPicPicture = new ActionParamsClass_GetPicPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPicPicture GetPicPictureParams { get { return s_params_GetPicPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPicPicture
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string natinalId = "natinalId";
        }
        static readonly ActionParamsClass_GetLocationRequest s_params_GetLocationRequest = new ActionParamsClass_GetLocationRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLocationRequest GetLocationRequestParams { get { return s_params_GetLocationRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLocationRequest
        {
            public readonly string AzmoonId = "AzmoonId";
            public readonly string Jobid = "Jobid";
            public readonly string GenderId = "GenderId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AzmoonDataTable = "_AzmoonDataTable";
                public readonly string _DataTable = "_DataTable";
                public readonly string _EditSahmiyeh = "_EditSahmiyeh";
                public readonly string _EditVlentear = "_EditVlentear";
                public readonly string _errorPrintData = "_errorPrintData";
                public readonly string _FilterBar = "_FilterBar";
                public readonly string _Index = "_Index";
                public readonly string _PrintData = "_PrintData";
                public readonly string _ReportSepratJobCity = "_ReportSepratJobCity";
                public readonly string _ReportValentear = "_ReportValentear";
                public readonly string _ReportValentearByAgahi = "_ReportValentearByAgahi";
                public readonly string _ReportValentearChairCard = "_ReportValentearChairCard";
                public readonly string _ReportValentearFillterGendederByAgahi = "_ReportValentearFillterGendederByAgahi";
                public readonly string _RSJCSA = "_RSJCSA";
                public readonly string _Search = "_Search";
                public readonly string GetFishPicture = "GetFishPicture";
                public readonly string ViewDataBeforSave = "ViewDataBeforSave";
            }
            public readonly string _AzmoonDataTable = "~/Areas/Admin/Views/Valentear/_AzmoonDataTable.cshtml";
            public readonly string _DataTable = "~/Areas/Admin/Views/Valentear/_DataTable.cshtml";
            public readonly string _EditSahmiyeh = "~/Areas/Admin/Views/Valentear/_EditSahmiyeh.cshtml";
            public readonly string _EditVlentear = "~/Areas/Admin/Views/Valentear/_EditVlentear.cshtml";
            public readonly string _errorPrintData = "~/Areas/Admin/Views/Valentear/_errorPrintData.cshtml";
            public readonly string _FilterBar = "~/Areas/Admin/Views/Valentear/_FilterBar.cshtml";
            public readonly string _Index = "~/Areas/Admin/Views/Valentear/_Index.cshtml";
            public readonly string _PrintData = "~/Areas/Admin/Views/Valentear/_PrintData.cshtml";
            public readonly string _ReportSepratJobCity = "~/Areas/Admin/Views/Valentear/_ReportSepratJobCity.cshtml";
            public readonly string _ReportValentear = "~/Areas/Admin/Views/Valentear/_ReportValentear.cshtml";
            public readonly string _ReportValentearByAgahi = "~/Areas/Admin/Views/Valentear/_ReportValentearByAgahi.cshtml";
            public readonly string _ReportValentearChairCard = "~/Areas/Admin/Views/Valentear/_ReportValentearChairCard.cshtml";
            public readonly string _ReportValentearFillterGendederByAgahi = "~/Areas/Admin/Views/Valentear/_ReportValentearFillterGendederByAgahi.cshtml";
            public readonly string _RSJCSA = "~/Areas/Admin/Views/Valentear/_RSJCSA.cshtml";
            public readonly string _Search = "~/Areas/Admin/Views/Valentear/_Search.cshtml";
            public readonly string GetFishPicture = "~/Areas/Admin/Views/Valentear/GetFishPicture.cshtml";
            public readonly string ViewDataBeforSave = "~/Areas/Admin/Views/Valentear/ViewDataBeforSave.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ValentearController : Jazb.Web.Areas.Admin.Controllers.ValentearController
    {
        public T4MVC_ValentearController() : base(Dummy.Instance) { }

        [NonAction]
        partial void UpdateamountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Updateamount()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Updateamount);
            UpdateamountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(int? AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            SearchOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void CreateChairNumberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateChairNumber(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateChairNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            CreateChairNumberOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void DataTableOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, int page, int count, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy);

        [NonAction]
        public override System.Web.Mvc.ActionResult DataTable(string term, int page, int count, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataTable);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchBy", searchBy);
            DataTableOverride(callInfo, term, page, count, searchBy);
            return callInfo;
        }

        [NonAction]
        partial void GetDataTableByAzmoonOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? AzmoonId, string term, int page, int count, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetDataTableByAzmoon(int? AzmoonId, string term, int page, int count, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDataTableByAzmoon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchBy", searchBy);
            GetDataTableByAzmoonOverride(callInfo, AzmoonId, term, page, count, searchBy);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string NationalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int AzmoonId, string NationalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "NationalId", NationalId);
            EditOverride(callInfo, AzmoonId, NationalId);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.RegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(Jazb.Model.ValentearModel.RegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            EditOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void SaveDateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.RegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDate(Jazb.Model.ValentearModel.RegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            SaveDateOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void EditNOIDOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditNOID()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditNOID);
            EditNOIDOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditSahmiyehOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string NationalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSahmiyeh(int AzmoonId, string NationalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSahmiyeh);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "NationalId", NationalId);
            EditSahmiyehOverride(callInfo, AzmoonId, NationalId);
            return callInfo;
        }

        [NonAction]
        partial void EditSahmiyehOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.RegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSahmiyeh(Jazb.Model.ValentearModel.RegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSahmiyeh);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            EditSahmiyehOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void AutoCompleteSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy);

        [NonAction]
        public override System.Web.Mvc.ActionResult AutoCompleteSearch(string term, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AutoCompleteSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchBy", searchBy);
            AutoCompleteSearchOverride(callInfo, term, searchBy);
            return callInfo;
        }

        [NonAction]
        partial void BlockValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string vid, string term1, int page1, int count1, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy1);

        [NonAction]
        public override System.Web.Mvc.ActionResult BlockValentear(string vid, string term1, int page1, int count1, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy1)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BlockValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vid", vid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term1", term1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page1", page1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count1", count1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchBy1", searchBy1);
            BlockValentearOverride(callInfo, vid, term1, page1, count1, searchBy1);
            return callInfo;
        }

        [NonAction]
        partial void StatusAcceptValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int ValentearId, int AcceptStatus, string Message);

        [NonAction]
        public override System.Web.Mvc.ActionResult StatusAcceptValentear(int ValentearId, int AcceptStatus, string Message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StatusAcceptValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ValentearId", ValentearId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AcceptStatus", AcceptStatus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Message", Message);
            StatusAcceptValentearOverride(callInfo, ValentearId, AcceptStatus, Message);
            return callInfo;
        }

        [NonAction]
        partial void BlockValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string vid, string term1, int page1, int count1, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy1);

        [NonAction]
        public override System.Web.Mvc.ActionResult BlockValentear(int AzmoonId, string vid, string term1, int page1, int count1, Jazb.Servicelayer.EFServices.Enums.ValentearSearchBy searchBy1)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BlockValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vid", vid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term1", term1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page1", page1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count1", count1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchBy1", searchBy1);
            BlockValentearOverride(callInfo, AzmoonId, vid, term1, page1, count1, searchBy1);
            return callInfo;
        }

        [NonAction]
        partial void PrintDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintData()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintData);
            PrintDataOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrintDataByMelicodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string natinalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintDataByMelicode(int AzmoonId, string natinalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDataByMelicode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "natinalId", natinalId);
            PrintDataByMelicodeOverride(callInfo, AzmoonId, natinalId);
            return callInfo;
        }

        [NonAction]
        partial void ReportValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportValentear(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportValentearOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ReportSepratJobCityOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportSepratJobCity(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportSepratJobCity);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportSepratJobCityOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ReportSepratJobCitySortByAghiOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportSepratJobCitySortByAghi(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportSepratJobCitySortByAghi);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportSepratJobCitySortByAghiOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ReportValentearByAgahiOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportValentearByAgahi(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearByAgahi);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportValentearByAgahiOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ReportValentearFillterGendederByAgahiOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportValentearFillterGendederByAgahi(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearFillterGendederByAgahi);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportValentearFillterGendederByAgahiOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void ReportValentearChairCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportValentearChairCard(int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportValentearChairCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ReportValentearChairCardOverride(callInfo, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void GetFishPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string natinalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFishPicture(int AzmoonId, string natinalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFishPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "natinalId", natinalId);
            GetFishPictureOverride(callInfo, AzmoonId, natinalId);
            return callInfo;
        }

        [NonAction]
        partial void GetTargPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string natinalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetTargPicture(int AzmoonId, string natinalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTargPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "natinalId", natinalId);
            GetTargPictureOverride(callInfo, AzmoonId, natinalId);
            return callInfo;
        }

        [NonAction]
        partial void GetPicPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, string natinalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPicPicture(int AzmoonId, string natinalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPicPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "natinalId", natinalId);
            GetPicPictureOverride(callInfo, AzmoonId, natinalId);
            return callInfo;
        }

        [NonAction]
        partial void GetLocationRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AzmoonId, int? Jobid, int? GenderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetLocationRequest(int AzmoonId, int? Jobid, int? GenderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetLocationRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AzmoonId", AzmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Jobid", Jobid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "GenderId", GenderId);
            GetLocationRequestOverride(callInfo, AzmoonId, Jobid, GenderId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
