// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Controllers
{
    public partial class PaymentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PaymentController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PaymentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowDataPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowDataPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendRequestPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendRequestPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReturnOfBank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReturnOfBank);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PaymentController Actions { get { return MVC.Payment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Payment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Payment";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PIndex = "PIndex";
            public readonly string Index = "Index";
            public readonly string PShowDataPayment = "PShowDataPayment";
            public readonly string ShowDataPayment = "ShowDataPayment";
            public readonly string SendRequestPayment = "SendRequestPayment";
            public readonly string ReturnOfBank = "ReturnOfBank";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PIndex = "PIndex";
            public const string Index = "Index";
            public const string PShowDataPayment = "PShowDataPayment";
            public const string ShowDataPayment = "ShowDataPayment";
            public const string SendRequestPayment = "SendRequestPayment";
            public const string ReturnOfBank = "ReturnOfBank";
        }


        static readonly ActionParamsClass_PIndex s_params_PIndex = new ActionParamsClass_PIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PIndex PIndexParams { get { return s_params_PIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PIndex
        {
            public readonly string AID = "AID";
            public readonly string Vid = "Vid";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string AID = "AID";
        }
        static readonly ActionParamsClass_ShowDataPayment s_params_ShowDataPayment = new ActionParamsClass_ShowDataPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowDataPayment ShowDataPaymentParams { get { return s_params_ShowDataPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowDataPayment
        {
            public readonly string vpayment = "vpayment";
        }
        static readonly ActionParamsClass_SendRequestPayment s_params_SendRequestPayment = new ActionParamsClass_SendRequestPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendRequestPayment SendRequestPaymentParams { get { return s_params_SendRequestPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendRequestPayment
        {
            public readonly string Pay = "Pay";
        }
        static readonly ActionParamsClass_ReturnOfBank s_params_ReturnOfBank = new ActionParamsClass_ReturnOfBank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReturnOfBank ReturnOfBankParams { get { return s_params_ReturnOfBank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReturnOfBank
        {
            public readonly string paymentId = "paymentId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string DontPayment = "DontPayment";
                public readonly string Index = "Index";
                public readonly string ReturnOfBank = "ReturnOfBank";
                public readonly string ShowDataPayment = "ShowDataPayment";
            }
            public readonly string DontPayment = "~/Views/Payment/DontPayment.cshtml";
            public readonly string Index = "~/Views/Payment/Index.cshtml";
            public readonly string ReturnOfBank = "~/Views/Payment/ReturnOfBank.cshtml";
            public readonly string ShowDataPayment = "~/Views/Payment/ShowDataPayment.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PaymentController : Jazb.Web.Controllers.PaymentController
    {
        public T4MVC_PaymentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID, int Vid);

        [NonAction]
        public override System.Web.Mvc.ActionResult PIndex(int AID, int Vid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Vid", Vid);
            PIndexOverride(callInfo, AID, Vid);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            IndexOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void PShowDataPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PShowDataPayment()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PShowDataPayment);
            PShowDataPaymentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ShowDataPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.Payment.VewPayment vpayment);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowDataPayment(Jazb.Model.Payment.VewPayment vpayment)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowDataPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vpayment", vpayment);
            ShowDataPaymentOverride(callInfo, vpayment);
            return callInfo;
        }

        [NonAction]
        partial void SendRequestPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.DomainClasses.Entities.Payment Pay);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendRequestPayment(Jazb.DomainClasses.Entities.Payment Pay)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendRequestPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Pay", Pay);
            SendRequestPaymentOverride(callInfo, Pay);
            return callInfo;
        }

        [NonAction]
        partial void ReturnOfBankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string paymentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReturnOfBank(string paymentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReturnOfBank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "paymentId", paymentId);
            ReturnOfBankOverride(callInfo, paymentId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
