// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Controllers
{
    public partial class SanjeshController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SanjeshController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SanjeshController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CheckData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CheckData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SanjeshController Actions { get { return MVC.Sanjesh; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Sanjesh";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Sanjesh";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CheckData = "CheckData";
            public readonly string ViewDataBeforeSave = "ViewDataBeforeSave";
            public readonly string SaveDate = "SaveDate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CheckData = "CheckData";
            public const string ViewDataBeforeSave = "ViewDataBeforeSave";
            public const string SaveDate = "SaveDate";
        }


        static readonly ActionParamsClass_CheckData s_params_CheckData = new ActionParamsClass_CheckData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckData CheckDataParams { get { return s_params_CheckData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckData
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SaveDate s_params_SaveDate = new ActionParamsClass_SaveDate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDate SaveDateParams { get { return s_params_SaveDate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDate
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string BeforeSave = "BeforeSave";
                public readonly string Index = "Index";
                public readonly string PrintDataSanjesh = "PrintDataSanjesh";
                public readonly string UploadPicture = "UploadPicture";
            }
            public readonly string BeforeSave = "~/Views/Sanjesh/BeforeSave.cshtml";
            public readonly string Index = "~/Views/Sanjesh/Index.cshtml";
            public readonly string PrintDataSanjesh = "~/Views/Sanjesh/PrintDataSanjesh.cshtml";
            public readonly string UploadPicture = "~/Views/Sanjesh/UploadPicture.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SanjeshController : Jazb.Web.Controllers.SanjeshController
    {
        public T4MVC_SanjeshController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CheckDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.Sanjesh.LoginSanjesh model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CheckData(Jazb.Model.Sanjesh.LoginSanjesh model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CheckData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CheckDataOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewDataBeforeSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewDataBeforeSave()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewDataBeforeSave);
            ViewDataBeforeSaveOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveDateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.Sanjesh.PrintDataSanjeshModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDate(Jazb.Model.Sanjesh.PrintDataSanjeshModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveDateOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
