// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Jazb.Web.Controllers
{
    public partial class ValentearController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ValentearController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BeforeRegister()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BeforeRegister);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Register()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditRegister()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditRegister);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditValentear()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditValentear);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintDataByMelicode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDataByMelicode);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IsNationalId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IsNationalId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetLocationRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetLocationRequest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ValentearController Actions { get { return MVC.Valentear; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Valentear";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Valentear";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string BeforeRegister = "BeforeRegister";
            public readonly string Register = "Register";
            public readonly string SaveData = "SaveData";
            public readonly string EditRegister = "EditRegister";
            public readonly string EditValentear = "EditValentear";
            public readonly string EditData = "EditData";
            public readonly string PrintData = "PrintData";
            public readonly string PrintDataByMelicode = "PrintDataByMelicode";
            public readonly string ViewCard = "ViewCard";
            public readonly string PrintCard = "PrintCard";
            public readonly string DontAccept = "DontAccept";
            public readonly string EditSahmiyeh = "EditSahmiyeh";
            public readonly string IsNationalId = "IsNationalId";
            public readonly string GetLocationRequest = "GetLocationRequest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string BeforeRegister = "BeforeRegister";
            public const string Register = "Register";
            public const string SaveData = "SaveData";
            public const string EditRegister = "EditRegister";
            public const string EditValentear = "EditValentear";
            public const string EditData = "EditData";
            public const string PrintData = "PrintData";
            public const string PrintDataByMelicode = "PrintDataByMelicode";
            public const string ViewCard = "ViewCard";
            public const string PrintCard = "PrintCard";
            public const string DontAccept = "DontAccept";
            public const string EditSahmiyeh = "EditSahmiyeh";
            public const string IsNationalId = "IsNationalId";
            public const string GetLocationRequest = "GetLocationRequest";
        }


        static readonly ActionParamsClass_BeforeRegister s_params_BeforeRegister = new ActionParamsClass_BeforeRegister();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BeforeRegister BeforeRegisterParams { get { return s_params_BeforeRegister; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BeforeRegister
        {
            public readonly string AID = "AID";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string AID = "AID";
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_SaveData s_params_SaveData = new ActionParamsClass_SaveData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveData SaveDataParams { get { return s_params_SaveData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveData
        {
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_EditRegister s_params_EditRegister = new ActionParamsClass_EditRegister();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditRegister EditRegisterParams { get { return s_params_EditRegister; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditRegister
        {
            public readonly string AID = "AID";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditValentear s_params_EditValentear = new ActionParamsClass_EditValentear();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditValentear EditValentearParams { get { return s_params_EditValentear; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditValentear
        {
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_EditData s_params_EditData = new ActionParamsClass_EditData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditData EditDataParams { get { return s_params_EditData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditData
        {
            public readonly string RM = "RM";
        }
        static readonly ActionParamsClass_PrintDataByMelicode s_params_PrintDataByMelicode = new ActionParamsClass_PrintDataByMelicode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintDataByMelicode PrintDataByMelicodeParams { get { return s_params_PrintDataByMelicode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintDataByMelicode
        {
            public readonly string azmoonzid = "azmoonzid";
            public readonly string natinalId = "natinalId";
        }
        static readonly ActionParamsClass_ViewCard s_params_ViewCard = new ActionParamsClass_ViewCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewCard ViewCardParams { get { return s_params_ViewCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewCard
        {
            public readonly string AID = "AID";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_IsNationalId s_params_IsNationalId = new ActionParamsClass_IsNationalId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IsNationalId IsNationalIdParams { get { return s_params_IsNationalId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IsNationalId
        {
            public readonly string nationalid = "Valentear.NationalID";
            public readonly string AzmoonId = "Valentear.AzmoonId";
        }
        static readonly ActionParamsClass_GetLocationRequest s_params_GetLocationRequest = new ActionParamsClass_GetLocationRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLocationRequest GetLocationRequestParams { get { return s_params_GetLocationRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLocationRequest
        {
            public readonly string azmoonId = "azmoonId";
            public readonly string Jobid = "Jobid";
            public readonly string GenderId = "GenderId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _errorPrintData = "_errorPrintData";
                public readonly string BeforeRegister = "BeforeRegister";
                public readonly string DontAccept = "DontAccept";
                public readonly string EditRegister = "EditRegister";
                public readonly string EditValentear = "EditValentear";
                public readonly string PrintCard = "PrintCard";
                public readonly string PrintData = "PrintData";
                public readonly string Register = "Register";
                public readonly string ViewCard = "ViewCard";
                public readonly string ViewDataBeforEdit = "ViewDataBeforEdit";
                public readonly string ViewDataBeforSave = "ViewDataBeforSave";
            }
            public readonly string _errorPrintData = "~/Views/Valentear/_errorPrintData.cshtml";
            public readonly string BeforeRegister = "~/Views/Valentear/BeforeRegister.cshtml";
            public readonly string DontAccept = "~/Views/Valentear/DontAccept.cshtml";
            public readonly string EditRegister = "~/Views/Valentear/EditRegister.cshtml";
            public readonly string EditValentear = "~/Views/Valentear/EditValentear.cshtml";
            public readonly string PrintCard = "~/Views/Valentear/PrintCard.cshtml";
            public readonly string PrintData = "~/Views/Valentear/PrintData.cshtml";
            public readonly string Register = "~/Views/Valentear/Register.cshtml";
            public readonly string ViewCard = "~/Views/Valentear/ViewCard.cshtml";
            public readonly string ViewDataBeforEdit = "~/Views/Valentear/ViewDataBeforEdit.cshtml";
            public readonly string ViewDataBeforSave = "~/Views/Valentear/ViewDataBeforSave.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ValentearController : Jazb.Web.Controllers.ValentearController
    {
        public T4MVC_ValentearController() : base(Dummy.Instance) { }

        [NonAction]
        partial void BeforeRegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult BeforeRegister(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BeforeRegister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            BeforeRegisterOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void BeforeRegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.Payment.BeforeRegisterModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult BeforeRegister(Jazb.Model.Payment.BeforeRegisterModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BeforeRegister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            BeforeRegisterOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            RegisterOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.RegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register(Jazb.Model.ValentearModel.RegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            RegisterOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void SaveDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.RegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveData(Jazb.Model.ValentearModel.RegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            SaveDataOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void EditRegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditRegister(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditRegister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            EditRegisterOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void EditRegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.AdminModel.EditValentear.EditVlentearPageVeiwMode model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditRegister(Jazb.Model.AdminModel.EditValentear.EditVlentearPageVeiwMode model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditRegister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditRegisterOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditValentearOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.EditRegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditValentear(Jazb.Model.ValentearModel.EditRegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditValentear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            EditValentearOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void EditDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.EditRegisterModel RM);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditData(Jazb.Model.ValentearModel.EditRegisterModel RM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RM", RM);
            EditDataOverride(callInfo, RM);
            return callInfo;
        }

        [NonAction]
        partial void PrintDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintData()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintData);
            PrintDataOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrintDataByMelicodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int azmoonzid, string natinalId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintDataByMelicode(int azmoonzid, string natinalId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDataByMelicode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "azmoonzid", azmoonzid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "natinalId", natinalId);
            PrintDataByMelicodeOverride(callInfo, azmoonzid, natinalId);
            return callInfo;
        }

        [NonAction]
        partial void ViewCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int AID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewCard(int AID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AID", AID);
            ViewCardOverride(callInfo, AID);
            return callInfo;
        }

        [NonAction]
        partial void ViewCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jazb.Model.ValentearModel.ViewCardModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewCard(Jazb.Model.ValentearModel.ViewCardModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ViewCardOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PrintCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCard()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCard);
            PrintCardOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DontAcceptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DontAccept()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DontAccept);
            DontAcceptOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditSahmiyehOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSahmiyeh()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSahmiyeh);
            EditSahmiyehOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IsNationalIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nationalid, int AzmoonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult IsNationalId(string nationalid, int AzmoonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IsNationalId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Valentear.NationalID", nationalid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Valentear.AzmoonId", AzmoonId);
            IsNationalIdOverride(callInfo, nationalid, AzmoonId);
            return callInfo;
        }

        [NonAction]
        partial void GetLocationRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int azmoonId, int? Jobid, int? GenderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetLocationRequest(int azmoonId, int? Jobid, int? GenderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetLocationRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "azmoonId", azmoonId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Jobid", Jobid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "GenderId", GenderId);
            GetLocationRequestOverride(callInfo, azmoonId, Jobid, GenderId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
